name: Deploy with Deployment Event

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create deployment
        id: create_deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{"ref":"main","environment":"github-pages","required_contexts":[]}')

          echo "response=$response"
          deployment_id=$(echo $response | jq -r '.id')
          echo "deployment_id=$deployment_id"
          echo "::set-output name=deployment_id::$deployment_id"

      - name: Run your deployment here
        run: echo "Replace this step with your actual deployment commands"

      - name: Mark deployment status as success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deployment_id=${{ steps.create_deployment.outputs.deployment_id }}
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/$deployment_id/statuses \
            -d '{"state":"success"}'
